################################################################################
### generated-with:
###   type: R-package
###   name: kwb.pkgbuild
###   version: 0.2.1
###   installed-from: https://kwb-r.r-universe.dev (R 4.1.3)
###   installed-on: '2022-04-14'
### generated-by:
###   user: mrustl
###   function-call: kwb.pkgbuild::create_empty_branch_ghpages("iphreeqc", org = "mrustl")
### generated-on: 2022-05-04 16:40:06
################################################################################


pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - gh-pages
